### ISSUE TITLE
Add shape to clusters

### ISSUE THREAD

**Issue by PavelTurk** [jamisonjiang/graph-support#4]
Currently we can add shape only to nodes:
```
Node A = Node.builder().label("A").shape(shape).build();
```
However, it would be very nice if it were possible to add shapes to clusters. Although it is not a standard graphviz feature it is possible to do - https://forum.graphviz.org/t/clusters-outline-geometry-attribute/313/2 

So, I suggest to add something like this 
```
Cluster.builder().shape(shape)...
```
or like this (to show it is not standard) :
```
ShapedCluster.builder().shape(shape)...
```
The reason is that it is very often necessary to add shapes not only to nodes but also for containers: For example, in UML:

![image](https://github.com/jamisonjiang/graph-support/assets/10261361/b5ec7b86-a7ff-4afc-86c2-856d5263c655)

If this feature is implemented then I think it is also necessary to add possibility to add edges between clusters and between clusters and nodes.

**Comment by jamisonjiang** [comment]
Good idea, Maybe I can try and only need small changed for current code architecture, but the hardest part is that considered the overlap between clusters if have multi cluster shapes, because per shape which not rectangle should have outer and inner container size and should detected the outer container size as the original rectangle in anticipation of enough space to avoid overlap with other clusters.
For the cluster edges, both the Graphviz [compound](https://graphviz.org/docs/attrs/compound) and graph-support [Example GraphAttrTest#compoundCases](https://github.com/jamisonjiang/graph-support/blob/main/src/test/java/visual_case/GraphAttrTest.java) are supported line cut by cluster border, but [PlantUML](https://github.com/plantuml/plantuml) used another heuristic way to implemented similar request by standard Graphviz, first split the original graph to multiple graphs without cluster and rendered one by one with nested order and detected rendered graph size as the size of parent node size to continue parent graph rendered, so maybe have another way to implement this request and without change original cluster feature.

We can adds Graph-Label feature learned from PlantUML heuristic method to perfect implemented the multi-shapes cluster and cluster edges request like following, and cluster concept transfer to node as the similar result but I think it is enormous challenge.
```java
Node n = Node.builder()
    .shape(NodeShapeEnum.TRIANGLE)
    .graphLabel(
        Graphviz.digraph()
            ...
            .build()
    )
    .build()
```

**Comment by jamisonjiang** [comment]
If nested graph in node we can not connect "child" node to "parent" node, this is meaning of cluster existence. Cluster and nest graph complementary each other, so the criterion when choose nest graph or cluster is whether needed connect the inner node to outside node.
Because recursive graph it means node only care the child graph size rather than the layout, but cluster is a part of original graph and participated all layout phases like rank assigned/mincross/position, there are totally difference but seems like similar in some scenarios.
Following case show a different result when use "nested" and "cluster" respectively:
![image](https://github.com/jamisonjiang/graph-support/assets/125274994/09a691e3-1b2e-4bf9-97ed-a8aacbe925e0)

**Comment by jamisonjiang** [comment]
@PavelTurk Just a example with dot:
```dot
digraph G {
    compound=true
    rankdir=LR
    node[shape=rect]
    a->d[dir=back label="requires" ltail="cluster_0" lhead="cluster_2"]
    b->e[label="exports" lhead="cluster_2"]
    b->e[dir=back label="opens" ltail="cluster_0"]
    subgraph cluster_0 {
        label="ModuleA"
        subgraph cluster_1 {
            label="coo.foo"
            a[label="api"]
            b[label="internal"]
        }
    }
  
    subgraph cluster_2 {
        label="ModuleB"
        subgraph cluster_3 {
            label="com.bar"
            d->e[minlen=0 style=invis]
            d[style=invis fixedsize=true height=0]
            e[label="impl"]
        }
    }
}
```
![image](https://github.com/jamisonjiang/graph-support/assets/125274994/cd47170e-7446-4a9b-809e-4a8b8de67c91)

**Comment by jamisonjiang** [comment]
First I will try multi cluster shapes and graph nested in the future, then I can give you some heavier solutions.
**graphviz-java**
If you want to use original graphviz in java (by the way graph-support is just use the same algorithm re-implementation but do not have any relationship with graphviz) you can try [graphviz-java](https://github.com/nidi3/graphviz-java), it is compile the graphviz to Javascript and try to use V8 javascript engine (a js engine of java) to run the js version of graphviz, and it is a more proven solution rather than create JNI interface by yourself, it is obviously heavier but more close to graphviz than graph-support
**PlantUml**
[PlantUML](https://github.com/plantuml/plantuml) is a versatile component that enables swift and straightforward diagram creation, and it write by java and provide scripts and java api for users. PlantUML use the graphviz as the layout engine to caculated the node coordinate but have independent rendered engine. I think PlantUML it is good choice because it have richer features and already used multi ways to integrate graphviz and do downgrade by your enviroment:
* If download graphviz on local environment and will caculate by local (same as graphviz-java);
* If not download graphviz, try use another project [smetana](https://github.com/plantuml/smetana/tree/V2_38)(a crazy project try to translate c code to java code, but not done as I know) if this project can cover the functions;
* If detected the java js engine and use the Vizjs(same as graphviz-java).

Finally, only the PlantUML + smetana is not have other dependency seems like graph-support, so you can try all these solutions to integrate to your project without create JNI by yourself and hope helpful for you.

**Comment by jamisonjiang** [comment]
All shapes consists of inner and outer boxes, all elements in shape should within inner box. graph-support use [ShapePropCalc#minContainerSize](https://github.com/jamisonjiang/graph-support/blob/main/src/main/java/org/graphper/api/ext/ShapePropCalc.java) to describing size relationship between inner and outer boxes and auto calculate right size to node.
So more safe that not overflow elements if more less gap of size between inner and outer boxes for specific cluster shape.
The shape STAR more easy occurred overflow issue because of large gap between inner and outer boxes liking following example:
![image](https://github.com/jamisonjiang/graph-support/assets/125274994/285f5931-7b5e-4ac7-a784-e43e0f9d28b3)

**Comment by jamisonjiang** [comment]
@PavelTurk Latest version supported multi cluster shape but have limitation I listed below, Cluster shapes except [ClusterShapeEnum](https://github.com/jamisonjiang/graph-support/blob/main/src/main/java/org/graphper/api/attributes/ClusterShapeEnum.java)#RECT no guarantee that cluster container will surround all nodes under Layout.DOT engine but will try best estimated the container size.
Both node shape and cluster shape can extension by [CustomizeShapeRender](https://github.com/jamisonjiang/graph-support/blob/main/src/main/java/org/graphper/draw/CustomizeShapeRender.java) to customized the specific shape by yourself.
![image](https://github.com/jamisonjiang/graph-support/assets/125274994/c30b6e3e-c13d-451f-8eb4-863106309a81)
